name: Enforce branch rules

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch_main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch main
        run: |
          if [[ "${{ github.head_ref }}" != "develop" && ! "${{ github.head_ref }}" =~ ^hotfix/ ]]; then
            echo "ERROR: You can only merge to main from develop or hotfix/*."
            exit 1
          fi
